### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by awrog** [finanalyst/grav-plugin-sqlite#1]
Nice plugin and great possibilities!!
Is it possible to extend the documentation with an example Form Action `sql-select` (create a form which will generate a SELECT statement, based on values from the form and displaying the result of this SELECT)?
Thnx!

**Comment by finanalyst** [comment]
There is an example in the documentation for both `sql-insert` and `sql-update`
There is no form action `sql-select`. The SQL SELECT statement is for retrieving data from a database, whereas INSERT and UPDATE are for adding/modifying. That is SELECT is from the database to the website, and INSERT/UPDATE are from the website to the database. Since these are different directions, two different approaches are used, viz. shortcode for SELECT and FORM for INSERT/UPDATE.

Hope this helps.
