### ISSUE TITLE
Multiple Forms

### ISSUE THREAD

**Issue by dlannan** [finanalyst/grav-plugin-sqlite#6]
The forms plugin has a multiple forms format. 
I have been trying to use this format with this plugin with no success - is there a specific way to do this?
Does it support multiple forms in the blueprint?
Thanks in advance.

**Comment by finanalyst** [comment]
I use multiple forms all the time with this plugin. Try looking at mgc.1ptd.com which is built using Grav, the sqlite plugin, datatables (another Grav plugin I wrote), multiple forms. Click on a hiker in the table, that sets up a field that is then used to interrogate an sqlite database. On the same page is a table to select the type of map being used. In fact, most of the plugins I wrote are related to websites I have created.

In order to get these more complex effects, you need to include some javascript and sql programming.

If you could be a bit more specific about what you want, I might be able to answer you in a way that is helpful. Also if you were to ask on the discuss forum, the question/answer might help others.

Regarding the blueprint question. I like to make things as generic as possible. However, there is a real problem about what is intuitive. How exactly do you think a blueprint for multiple forms should work? I'm genuinely curious. If you could suggest a User Interface that would solve your specific problem and could be abstracted into something that is generic for others, then I would love to try to implement it.

**Comment by dlannan** [comment]
Hi, thanks for the response. Im referring to the use of the multiple forms support that the forms plugin uses, so in the blueprint you have like suggested in the forms documentation:
https://learn.getgrav.org/forms/forms  - see Multiple forms section.
This is what I have been trying to use unsuccessfully. 
Ive created my own sqlite twig extensions to allow me to do more complex behaviours anyway so I could move forward.

**Comment by finanalyst** [comment]
I have put some working code up on the Grav forum to show how I did it. See [multiple forms etc](https://discourse.getgrav.org/t/multiple-forms-datatables-sqlite-and-map/8289)

**Comment by finanalyst** [comment]
@dlannan , I wrote up the Grav forum item as you were answering me. The link is above. I have used the multiple forms feature in the code linked to. There is some twig on the page, but only to conditionally show / not show a form.

Although the multiple forms in the code example are created within the default.md (note it is not a form.md file) for the page itself, I have put forms in another page as discussed in the Forms plugin documentation. But I found that by keeping the form definition on the same page made it easier to understand the other code.

Hope this helps. Let me know if you were expecting some other behaviour.
